//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
using System.Collections.Generic;

namespace FlopManager.Domain
{

    public class LoanType
    {
        public LoanType()
        {
            Loans = new HashSet<Loan>();
            PaymentInstructions = new HashSet<PaymentInstruction>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Code { get; set; }

        [Required]
        [StringLength(50)]
        public string LoanDescription { get; set; }

        public virtual ICollection<Loan> Loans { get; set; }

        public virtual ICollection<PaymentInstruction> PaymentInstructions { get; set; }
        public override int GetHashCode()
        {
            int hash = 13;
            hash = hash*31 + Code.GetHashCode();
            return hash;
        }

        public override bool Equals(object obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            LoanType lt = (LoanType) obj;
            return Code == lt.Code;
        }
    }
}
