//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbm.ViewsModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fbm.ViewsModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير قار على جلب البيانات راجع التفاصيل التالية:.
        /// </summary>
        internal static string DbErrorMsg {
            get {
                return ResourceManager.GetString("DbErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في رقم المستحق.
        /// </summary>
        internal static string InvalidFamilyMemberCode {
            get {
                return ResourceManager.GetString("InvalidFamilyMemberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في رقم الدفعة.
        /// </summary>
        internal static string InvalidPaymentNo {
            get {
                return ResourceManager.GetString("InvalidPaymentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال وصف مختصر للألتزام.
        /// </summary>
        internal static string LoansView_DescriptionMissing {
            get {
                return ResourceManager.GetString("LoansView_DescriptionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبق تسجيل التزام من هذا النوع للمستحق على هذه الصرفية.
        /// </summary>
        internal static string LoansView_ExistMemberLoan {
            get {
                return ResourceManager.GetString("LoansView_ExistMemberLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيد الإلتزام لا يمكن أن يكون مديناً.
        /// </summary>
        internal static string LoansView_InsufBalance {
            get {
                return ResourceManager.GetString("LoansView_InsufBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد نوع الإلتزام.
        /// </summary>
        internal static string LoansView_LoanTypeMissing {
            get {
                return ResourceManager.GetString("LoansView_LoanTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد سنة الخصم.
        /// </summary>
        internal static string LoansView_LoanYearMissing {
            get {
                return ResourceManager.GetString("LoansView_LoanYearMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال بيانات المستحق.
        /// </summary>
        internal static string LoansView_MemberMissing {
            get {
                return ResourceManager.GetString("LoansView_MemberMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد دفعة الخصم.
        /// </summary>
        internal static string LoansView_PaySeqMissing {
            get {
                return ResourceManager.GetString("LoansView_PaySeqMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل مبلغ الإلتزام.
        /// </summary>
        internal static string LoansView_ZeroloanAmount {
            get {
                return ResourceManager.GetString("LoansView_ZeroloanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الإلتزام يجب ان يتكون من رقمين على الأقل.
        /// </summary>
        internal static string LoanTypesView_InvalidCode {
            get {
                return ResourceManager.GetString("LoanTypesView_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال وصف لنوع الإلتزام.
        /// </summary>
        internal static string LoanTypesView_MissingDescription {
            get {
                return ResourceManager.GetString("LoanTypesView_MissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد دفعات لهذه السنة.
        /// </summary>
        internal static string MemberPaymentView_NoPaymentSequ {
            get {
                return ResourceManager.GetString("MemberPaymentView_NoPaymentSequ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد إغلاق السنة الحالية؟.
        /// </summary>
        internal static string OptionView_PromptForCloseYear {
            get {
                return ResourceManager.GetString("OptionView_PromptForCloseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقصى حد للدفعات المسموح بها 12.
        /// </summary>
        internal static string PaymentSeqView_ExceedingSeqNo {
            get {
                return ResourceManager.GetString("PaymentSeqView_ExceedingSeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال تسلسل الصرفية.
        /// </summary>
        internal static string PaymentView_PaySeqMissing {
            get {
                return ResourceManager.GetString("PaymentView_PaySeqMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال سنة الصرفية.
        /// </summary>
        internal static string PaymentView_PayYearMissing {
            get {
                return ResourceManager.GetString("PaymentView_PayYearMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبق تسجيل هذه السنة.
        /// </summary>
        internal static string PeriodView_AlreadyRegistredYear {
            get {
                return ResourceManager.GetString("PeriodView_AlreadyRegistredYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن إغلاق السنة من هنا
        ///فضلاً قم بإغلاقها من خلال الخيارات.
        /// </summary>
        internal static string PeriodView_CannotSelectCloseStatus {
            get {
                return ResourceManager.GetString("PeriodView_CannotSelectCloseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن لتاريخ الانتهاء ان يسبق تاريخ البداية.
        /// </summary>
        internal static string PeriodView_InconsistentStartEndDate {
            get {
                return ResourceManager.GetString("PeriodView_InconsistentStartEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في تاريخ الإنتهاء.
        /// </summary>
        internal static string PeriodView_InvalidEndDate {
            get {
                return ResourceManager.GetString("PeriodView_InvalidEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن ان يكون هناك اكثر من سنة حالية.
        /// </summary>
        internal static string PeriodView_InvalidPeriodStatus {
            get {
                return ResourceManager.GetString("PeriodView_InvalidPeriodStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في تاريخ البداية.
        /// </summary>
        internal static string PeriodView_InvalidStartDate {
            get {
                return ResourceManager.GetString("PeriodView_InvalidStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد حالة السنة.
        /// </summary>
        internal static string PeriodView_PeriodStutsMissing {
            get {
                return ResourceManager.GetString("PeriodView_PeriodStutsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدائية والنهاية يجب ان يكون في نفس السنة.
        /// </summary>
        internal static string PeriodView_YearPartNotMatch {
            get {
                return ResourceManager.GetString("PeriodView_YearPartNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب على الأقل اضافة دفعة لهذه السنة.
        /// </summary>
        internal static string PeriodView_YearSeqMissing {
            get {
                return ResourceManager.GetString("PeriodView_YearSeqMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حذف البيانات؟.
        /// </summary>
        internal static string PromptForDeleteMsg {
            get {
                return ResourceManager.GetString("PromptForDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الخروج بدون حفظ؟.
        /// </summary>
        internal static string PromptForSaveMsg {
            get {
                return ResourceManager.GetString("PromptForSaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد مسار قاعدة بيانات المستحقين.
        /// </summary>
        internal static string SyncMembersView_FamilyDbMissing {
            get {
                return ResourceManager.GetString("SyncMembersView_FamilyDbMissing", resourceCulture);
            }
        }
    }
}
